### ISSUE TITLE
Where is source code?

### ISSUE THREAD

**Issue by Pyran1** [cnanney/dev-toolbox#3]
Yeah it is really wonderful extension, but I wanna see source this extension source code because I can't so easily believe that extension is not connecting anywhere.

**Comment by cnanney** [comment]
Hello, thanks for asking. I do eventually intend to add the source to this repo, and will leave this ticket open, but for now it is simply a landing page for information and bug reports.

Until then, know that if the extension did want to access any external resources I would have to [declare them in the manifest](https://developer.chrome.com/docs/extensions/mv3/xhr/#requesting-permission), and you'd be notified of this when installing. Also you can "inspect popup" in Chrome and see the network requests tab while using it to verify nothing is being sent.

**Comment by Pyran1** [comment]
Thanks for answer, I don't really use Chromium-based browsers, so "Inspect Popup" not really way to check any of the requests for me. About manifest, you still didn't upload source code, so I cannot check it. Again, thanks for the answer.

**Comment by Pyran1** [comment]
I found an easier way to check Firefox's extension manifest by using `about:debugging`. You need to open that link: `about:debugging#/runtime/this-firefox`, then found current extension, in final just click on URL in paragraph *Manifest URL***, okay, finally I can see manifest file, there is what I get:
```
{
  "name": "Dev Toolbox",
  "description": "Dev Toolbox provides quick offline access to various development tools.",
  "version": "1.0.5",
  "manifest_version": 2,
  "permissions": [
    "storage"
  ],
  "browser_action": {
    "default_popup": "index.html",
    "default_icon": {
      "16": "/img/tb_16.png",
      "24": "/img/tb_24.png"
    }
  },
  "icons": {
    "16": "/img/tb_16.png",
    "24": "/img/tb_24.png",
    "32": "/img/tb_32.png",
    "48": "/img/tb_48.png",
    "128": "/img/tb_128.png"
  },
  "browser_specific_settings": {
    "gecko": {
      "id": "{********-****-****-****-************}"
    }
  }
}
```
Thanks for helping me get manifest file, also little question, is there will be added SHADeep for **Hash** category, and you will add blob support for hash?

**Comment by cnanney** [comment]
Code is open source now 👍
